### ISSUE TITLE
doesn't apear in reports menu

### ISSUE THREAD

**Issue by MarcusWolschon** [technodelight/magento_custom_reports_example#5]
In Magento 1.9.1.1 the report isn't listed in any of the "Reports" sub-menues.
Even if the admin UI language is switched to English.

There is also no entry in any of the logs in app/var/log .
Something must have changed in recent Magento versions that is no longer compatible with this example report.

**Comment by rajukumargupta** [comment]
Hi 

it is returning only 21 rows . can you solve this issue

**Comment by MarcusWolschon** [comment]
I had to clear the caches. Silly mistake.

**Comment by technodelight** [comment]
Whenever you enable a module in admin you have to clear caches and log out / log in on the admin panel

**Comment by technodelight** [comment]
Hi Rajukumargupta, what would you like to display? I can't really help you if I don't know your intentions.

**Comment by MarcusWolschon** [comment]
I already said it's fixed.
There was no menu item "Berichte"->"Special Reports" at that time because I forgot to clear the caches.
(That's a point that should be mentioned in the readme.md by the way.)

**Comment by technodelight** [comment]
@MarcusWolschon that's fine, I just wanted to add this comment for the sake of history. 
 +1 fact: it's not always enough to clear the cache; if you have custom ACL defined to your controller, the user's ACL should be reloaded via a log out an re-login (due to the fact admin user ACLs are stored in the session while you are browsing the admin panel).
